#!/usr/bin/zsh

zmodload -i zsh/net/tcp

cd /myzshbot

until git pull -f; do
	sleep 1
done

while true; do 
	./irc.zsh
	sleep 1
done &

while true; do
	./http.zsh
	err=$?
	ztcp localhost 7000
	echo "msg #myzsh http.zsh crashed Err: $err" >&$REPLY
	ztcp -c $REPLY
	sleep 1
done
wait
